# Generated by Django 2.2 on 2019-05-07 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_resource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='ip',
            field=models.CharField(default='', max_length=128),
        ),
    ]
