# Generated by Django 2.2 on 2019-05-15 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0005_auto_20190507_0841'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host_All',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(default='0.0.0.0')),
                ('cpu_type', models.CharField(default='', max_length=128)),
                ('mem_scalable', models.IntegerField(default=0)),
                ('mem_slot', models.IntegerField(default=0)),
                ('server_type', models.CharField(default='', max_length=128)),
                ('server_producter', models.CharField(default='', max_length=64)),
                ('server_number', models.IntegerField(default=0)),
                ('gpu_info', models.CharField(default='', max_length=128)),
                ('network', models.CharField(default='{}', max_length=512)),
                ('root', models.CharField(default='{}', max_length=512)),
                ('data', models.CharField(default='{}', max_length=512)),
            ],
        ),
        migrations.RenameField(
            model_name='host',
            old_name='sn',
            new_name='kernel',
        ),
        migrations.RemoveField(
            model_name='host',
            name='over_insurance_time',
        ),
        migrations.AddField(
            model_name='host',
            name='cpu_core',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='host',
            name='cpu_thread',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='host',
            name='user',
            field=models.CharField(default='root', max_length=128),
        ),
    ]
