# Generated by Django 2.0 on 2019-08-08 13:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0004_auto_20190807_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host_All',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(default='0.0.0.0')),
                ('user', models.CharField(default='admin', max_length=128)),
                ('mac', models.CharField(default='', max_length=128)),
                ('cpu_name', models.CharField(default='', max_length=128)),
                ('server_producter', models.CharField(default='made in china', max_length=64)),
                ('server_name', models.CharField(default='', max_length=128)),
                ('serial', models.CharField(default='', max_length=128)),
                ('network', models.CharField(default='{}', max_length=512)),
                ('partitons', models.CharField(default='{}', max_length=512)),
                ('update_time', models.DateTimeField()),
            ],
        ),
        migrations.RenameField(
            model_name='host',
            old_name='cpu',
            new_name='cpu_number',
        ),
        migrations.RenameField(
            model_name='host',
            old_name='cpu_thread',
            new_name='cpu_vcore',
        ),
        migrations.RenameField(
            model_name='host',
            old_name='last_time',
            new_name='discover_time',
        ),
        migrations.RenameField(
            model_name='host',
            old_name='disk',
            new_name='disk_info',
        ),
        migrations.RemoveField(
            model_name='host',
            name='mem',
        ),
        migrations.AddField(
            model_name='host',
            name='mem_size',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='host',
            name='update_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='host',
            name='arch',
            field=models.CharField(default='X86', max_length=16),
        ),
        migrations.AlterField(
            model_name='host',
            name='kernel',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='host',
            name='name',
            field=models.CharField(default='', max_length=32),
        ),
    ]
