# Generated by Django 2.0 on 2019-08-08 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0005_auto_20190808_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host_all',
            name='server_name',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
