# Generated by Django 2.0 on 2019-08-12 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0008_auto_20190809_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host_all',
            name='cpu_name',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
