# Generated by Django 2.0 on 2019-08-21 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0009_auto_20190812_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='mem_size',
        ),
        migrations.AddField(
            model_name='host',
            name='gpu_info',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AddField(
            model_name='host',
            name='mem_info',
            field=models.CharField(default='[]', max_length=512),
        ),
        migrations.AlterField(
            model_name='host',
            name='arch',
            field=models.CharField(default='x86', max_length=16),
        ),
    ]
