# Generated by Django 2.0 on 2020-01-13 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0017_deploy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wealth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(default='0.0.0.0')),
                ('name', models.CharField(default='', max_length=32)),
                ('host_address', models.CharField(default='无', max_length=32)),
                ('service_role', models.CharField(default='', max_length=256)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('remark', models.TextField(default='无')),
            ],
        ),
        migrations.AlterField(
            model_name='deploy',
            name='remark',
            field=models.TextField(default='无'),
        ),
        migrations.AlterField(
            model_name='deploy',
            name='update_time',
            field=models.CharField(default='无时间', max_length=64),
        ),
    ]
