# Generated by Django 2.0 on 2020-04-07 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0003_auto_20200228_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview_options',
            name='question_number',
            field=models.TextField(default='无'),
        ),
        migrations.AlterField(
            model_name='interview_sort_answer',
            name='question_number',
            field=models.TextField(default='无'),
        ),
    ]
