# Generated by Django 2.0 on 2020-04-20 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0004_auto_20200407_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview_options',
            name='flag',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AddField(
            model_name='interview_sort_answer',
            name='flag',
            field=models.CharField(default='', max_length=16),
        ),
    ]
