# Generated by Django 2.0 on 2020-04-10 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='user',
            name='tel',
            field=models.CharField(default='无', max_length=32),
        ),
    ]
