# Generated by Django 2.2 on 2019-05-07 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20190424_0534'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hardware_Information',
        ),
    ]
