# Generated by Django 2.0 on 2019-08-09 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webanalysis', '0002_accesslog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accesslog',
            old_name='IP',
            new_name='ip',
        ),
        migrations.RenameField(
            model_name='accesslog',
            old_name='URL',
            new_name='url',
        ),
    ]
