# Generated by Django 2.2 on 2019-05-30 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.IntegerField(default=0)),
                ('ip', models.GenericIPAddressField(default='0.0.0.0')),
                ('url', models.CharField(default='', max_length=1024)),
                ('status_code', models.IntegerField(default=0)),
                ('access_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='AccessLogFileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128)),
                ('path', models.CharField(default='', max_length=1024)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
    ]
