# Generated by Django 2.0 on 2019-08-07 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_auto_20190807_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='mem',
            field=models.CharField(default='', max_length=64),
        ),
    ]
