# Generated by Django 2.0 on 2019-08-09 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0007_auto_20190808_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(default='0.0.0.0')),
                ('cpu', models.FloatField(default=0)),
                ('mem', models.FloatField(default=0)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='host',
            name='discover_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
