# Generated by Django 2.0 on 2019-08-21 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0010_auto_20190821_1538'),
    ]

    operations = [
        migrations.RenameField(
            model_name='host_all',
            old_name='partitons',
            new_name='partitions',
        ),
        migrations.AlterField(
            model_name='host_all',
            name='cpu_name',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='host_all',
            name='serial',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='host_all',
            name='server_name',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='host_all',
            name='user',
            field=models.CharField(default='admin', max_length=16),
        ),
    ]
