# Generated by Django 2.0 on 2019-08-27 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0011_auto_20190821_1636'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='cpu',
            new_name='cpu_total_use',
        ),
        migrations.RenameField(
            model_name='resource',
            old_name='mem',
            new_name='disk_read',
        ),
        migrations.AddField(
            model_name='resource',
            name='disk_write',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='resource',
            name='mem_free',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='resource',
            name='network_download',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='resource',
            name='network_total_use',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='resource',
            name='network_upload',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='resource',
            name='process_cpu_use',
            field=models.CharField(default='[]', max_length=512),
        ),
        migrations.AddField(
            model_name='resource',
            name='process_isalive',
            field=models.CharField(default='[]', max_length=512),
        ),
        migrations.AddField(
            model_name='resource',
            name='process_mem_use',
            field=models.CharField(default='[]', max_length=512),
        ),
        migrations.AlterField(
            model_name='host_all',
            name='partitions',
            field=models.CharField(default='{}', max_length=1024),
        ),
    ]
