# Generated by Django 2.0 on 2019-10-23 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0013_auto_20190923_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gpu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(default='0.0.0.0')),
                ('gpu_user', models.CharField(default='[]', max_length=1024)),
                ('gpu_mem', models.CharField(default='[]', max_length=1024)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='resource',
            name='process_cpu_use',
            field=models.CharField(default='[]', max_length=128),
        ),
        migrations.AlterField(
            model_name='resource',
            name='process_isalive',
            field=models.CharField(default='[]', max_length=128),
        ),
        migrations.AlterField(
            model_name='resource',
            name='process_mem_use',
            field=models.CharField(default='[]', max_length=128),
        ),
    ]
