# Generated by Django 2.0 on 2019-10-24 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0014_auto_20191023_1400'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gpu',
            old_name='gpu_mem',
            new_name='gpu_use_mem',
        ),
        migrations.RenameField(
            model_name='gpu',
            old_name='gpu_user',
            new_name='gpu_use_process',
        ),
        migrations.AddField(
            model_name='gpu',
            name='gpu_user_uid',
            field=models.CharField(default='[]', max_length=1024),
        ),
    ]
