# Generated by Django 2.0 on 2019-11-01 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0015_auto_20191024_1105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gpu',
            old_name='gpu_use_mem',
            new_name='gpu_user_name',
        ),
        migrations.RenameField(
            model_name='gpu',
            old_name='created_time',
            new_name='update_time',
        ),
        migrations.RemoveField(
            model_name='gpu',
            name='gpu_use_process',
        ),
        migrations.RemoveField(
            model_name='gpu',
            name='gpu_user_uid',
        ),
    ]
