# Generated by Django 2.0 on 2020-02-27 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0020_auto_20200223_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview_SA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(default='无', max_length=64)),
                ('question_number', models.IntegerField(default=0)),
                ('title', models.TextField(default='无')),
                ('question_answer', models.TextField(default='无')),
                ('scores', models.IntegerField(default=0)),
                ('update_time', models.DateTimeField()),
            ],
        ),
    ]
