# Generated by Django 2.0 on 2020-04-09 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0021_interview_sa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Interview',
        ),
        migrations.DeleteModel(
            name='Interview_SA',
        ),
    ]
