# Generated by Django 2.0 on 2020-04-10 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0022_auto_20200409_1319'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Host_All',
            new_name='Host_More',
        ),
    ]
