# Generated by Django 2.0 on 2020-04-10 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0023_auto_20200410_1258'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Resource',
            new_name='Monitor_Resource',
        ),
    ]
