# Generated by Django 2.0 on 2020-04-17 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0024_auto_20200410_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='host_more',
            name='project_name',
            field=models.CharField(default='ESD', max_length=64),
        ),
    ]
