# Generated by Django 2.0 on 2020-04-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0025_host_more_project_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host_more',
            name='project_name',
        ),
        migrations.AddField(
            model_name='host',
            name='project_name',
            field=models.CharField(default='ESD', max_length=64),
        ),
    ]
