# Generated by Django 2.0 on 2019-08-09 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webanalysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.IntegerField(default=0)),
                ('IP', models.CharField(default='', max_length=128)),
                ('URL', models.CharField(default='', max_length=1024)),
                ('status_code', models.IntegerField(default=0)),
                ('access_time', models.DateTimeField()),
            ],
        ),
    ]
