# Generated by Django 2.0 on 2020-02-28 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=32)),
                ('scores', models.IntegerField(default=0)),
                ('true_number', models.IntegerField(default=0)),
                ('false_number', models.IntegerField(default=0)),
                ('remark', models.TextField(default='无')),
                ('create_time', models.DateTimeField()),
            ],
        ),
    ]
