# Generated by Django 2.0 on 2020-03-25 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_scores'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scores',
            old_name='false_number',
            new_name='options_scores',
        ),
        migrations.RenameField(
            model_name='scores',
            old_name='true_number',
            new_name='short_scores',
        ),
    ]
