# Generated by Django 2.0 on 2020-03-25 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20200325_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scores',
            name='short_scores',
        ),
        migrations.AddField(
            model_name='scores',
            name='short_answer',
            field=models.CharField(default='', max_length=128),
        ),
    ]
