# Generated by Django 2.0 on 2020-03-31 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20200325_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='Other',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=32)),
                ('short_answer', models.CharField(default='', max_length=128)),
                ('interviewer_answer', models.TextField(default='无')),
                ('remark', models.TextField(default='无')),
                ('create_time', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='scores',
            name='remark',
        ),
        migrations.RemoveField(
            model_name='scores',
            name='short_answer',
        ),
        migrations.AddField(
            model_name='scores',
            name='short_answer_scores',
            field=models.IntegerField(default=0),
        ),
    ]
