# Generated by Django 2.0 on 2020-04-02 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20200331_1639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='tel',
            new_name='remark',
        ),
    ]
