# Generated by Django 2.0 on 2020-04-02 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20200402_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scores',
            name='short_answer_scores',
            field=models.CharField(default='0', max_length=32),
        ),
    ]
