# Generated by Django 2.0 on 2020-04-07 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20200403_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scores',
            name='short_answer_scores',
            field=models.TextField(default='0'),
        ),
    ]
