# Generated by Django 2.0 on 2020-04-20 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20200407_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('simple_title', models.CharField(default='[]', max_length=32)),
                ('medium_title', models.CharField(default='[]', max_length=32)),
                ('hard_title', models.CharField(default='[]', max_length=32)),
                ('create_time', models.DateTimeField()),
            ],
        ),
    ]
