# Generated by Django 2.0 on 2020-04-20 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_usertitle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertitle',
            old_name='hard_title',
            new_name='option_hard_title',
        ),
        migrations.RenameField(
            model_name='usertitle',
            old_name='medium_title',
            new_name='option_medium_title',
        ),
        migrations.RenameField(
            model_name='usertitle',
            old_name='simple_title',
            new_name='option_simple_title',
        ),
        migrations.AddField(
            model_name='usertitle',
            name='short_hard_title',
            field=models.CharField(default='[]', max_length=32),
        ),
        migrations.AddField(
            model_name='usertitle',
            name='short_medium_title',
            field=models.CharField(default='[]', max_length=32),
        ),
        migrations.AddField(
            model_name='usertitle',
            name='short_simple_title',
            field=models.CharField(default='[]', max_length=32),
        ),
    ]
