# Generated by Django 2.2 on 2019-05-07 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_auto_20190505_0305'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(default='0.0.0.0')),
                ('cpu', models.FloatField(default=0)),
                ('mem', models.FloatField(default=0)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
