# Generated by Django 2.2 on 2019-05-07 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0004_auto_20190507_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='ip',
            field=models.GenericIPAddressField(default='0.0.0.0'),
        ),
    ]
