# Generated by Django 2.2 on 2019-05-21 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0009_auto_20190521_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='cpu',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='mem',
        ),
        migrations.AddField(
            model_name='resource',
            name='gpu',
            field=models.CharField(default='[]', max_length=512),
        ),
    ]
