# Generated by Django 2.2 on 2019-04-24 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_hardware_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardware_information',
            name='Server_Number',
            field=models.IntegerField(default=0),
        ),
    ]
