# Generated by Django 2.2 on 2019-04-24 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190424_0518'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hardware_information',
            old_name='Data_Size',
            new_name='Describe',
        ),
        migrations.RemoveField(
            model_name='hardware_information',
            name='Cpu_Core',
        ),
        migrations.RemoveField(
            model_name='hardware_information',
            name='Cpu_Number',
        ),
        migrations.RemoveField(
            model_name='hardware_information',
            name='Cpu_Thread',
        ),
        migrations.RemoveField(
            model_name='hardware_information',
            name='Cpu_Type',
        ),
        migrations.RemoveField(
            model_name='hardware_information',
            name='Disk_Number',
        ),
        migrations.RemoveField(
            model_name='hardware_information',
            name='Disks_each_Size',
        ),
        migrations.RemoveField(
            model_name='hardware_information',
            name='GPU_Name',
        ),
        migrations.RemoveField(
            model_name='hardware_information',
            name='Gpu_Total_Mem',
        ),
        migrations.RemoveField(
            model_name='hardware_information',
            name='Kernel_Name',
        ),
        migrations.RemoveField(
            model_name='hardware_information',
            name='Mem_each_Size',
        ),
        migrations.RemoveField(
            model_name='hardware_information',
            name='Mem_scalable',
        ),
        migrations.RemoveField(
            model_name='hardware_information',
            name='Mem_slot_Number',
        ),
        migrations.RemoveField(
            model_name='hardware_information',
            name='Mem_total_Size',
        ),
        migrations.RemoveField(
            model_name='hardware_information',
            name='Network_Ip',
        ),
        migrations.RemoveField(
            model_name='hardware_information',
            name='Network_Mac',
        ),
        migrations.RemoveField(
            model_name='hardware_information',
            name='Network_Name',
        ),
        migrations.RemoveField(
            model_name='hardware_information',
            name='OS_Name',
        ),
        migrations.RemoveField(
            model_name='hardware_information',
            name='Root_Size',
        ),
        migrations.RemoveField(
            model_name='hardware_information',
            name='Server_Number',
        ),
        migrations.RemoveField(
            model_name='hardware_information',
            name='Server_Producter',
        ),
        migrations.RemoveField(
            model_name='hardware_information',
            name='Server_Type',
        ),
        migrations.RemoveField(
            model_name='hardware_information',
            name='create_time',
        ),
    ]
